### ISSUE TITLE
Not compatible with Prettier 3+

### ISSUE THREAD

**Issue by jamesgpearce** [mjeanroy/rollup-plugin-prettier#1343]
As subject! Is there any chance of a release that will allow npm to not complain about compatibility with Prettier 3.0.x? Thanks!

**Comment by mjeanroy** [comment]
Hi @jamesgpearce,

I just released version `v4.0.0` with support of prettier ^3.O.O.
Feel free to re-open an issue if something does not work as expected!

**Comment by jamesgpearce** [comment]
great, thanks @mjeanroy!
