### ISSUE TITLE
Support for prettier config

### ISSUE THREAD

**Issue by hosein2398** [mjeanroy/rollup-plugin-prettier#195]
There should be support for prettier config files,[ this method](https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath-options) can be used.

**Comment by mjeanroy** [comment]
Hi,
Thanks for your suggestion.
I'm not sure to understand your need, why don't you import your configuration like this:

```javascript
const prettier = require('rollup-plugin-prettier');

module.exports = {
  plugins: [
    prettier(require('./prettier.config.js')),
  ],
};
```

What use-case would you like to solve?

**Comment by mjeanroy** [comment]
@hosein2398 I understand, and I think you are right.

What do you think of allowing this option:

```javascript
const prettier = require('rollup-plugin-prettier');

module.exports = {
  plugins: [
    prettier({
      configFile: './config/prettier.config.js',
    }),
  ],
};
```

Or, if you want to have more control:

```javascript
const prettier = require('rollup-plugin-prettier');

module.exports = {
  plugins: [
    prettier({
      configFile: {
        path: './config/prettier.config.js',

        // Options available for method: https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath-options
        options: {
          useCache: false,
        },
      },
    }),
  ],
};
```

What do you think?

**Comment by hosein2398** [comment]
This is exactly what I suggested, but the maintainer did not accept, 
https://github.com/egoist/bili/pull/149#discussion_r232173580

And I think he is right tho

**Comment by mjeanroy** [comment]
Sorry, I'm not sure to understand. Can you explain how you think it should work?
Thanks again for the suggestion, that's an interesting discussion ;)

**Comment by hosein2398** [comment]
I guess [this method](https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath-options) detail explains well

**Comment by mjeanroy** [comment]
This commit add support for config file, it works by resolving the custom from current working directory (`process.cwd()`). It should works as long as the prettier config file is at the root of the package being built, otherwise it is possible to specify the current working directory:

```javascript
const path = require('path');
const prettier = require('rollup-plugin-prettier');

module.exports = {
  plugins: [
    prettier({
      cwd: path.join(__dirname, 'src'),
    }),
  ],
};
```

If that's ok for you, I'll release a new version.

**Comment by mjeanroy** [comment]
@hosein2398 Version 0.5.0 has been released with that improvement.
