### ISSUE TITLE
Add changelog or release notes

### ISSUE THREAD

**Issue by vladshcherbin** [mjeanroy/rollup-plugin-prettier#198]
Hey 👋 

It would be nice to have some kind of changelog, especially since the project was updated once a year.

Thank you :)

**Comment by mjeanroy** [comment]
Hi @vladshcherbin,
You're 100% right and I'm sorry I missed it, I'll add it (I'll close this issue once added).

**Comment by vladshcherbin** [comment]
I think this can be closed now. Thank you 🎉
