### ISSUE TITLE
Not able to use this plugin with rollup v0.67.1

### ISSUE THREAD

**Issue by yugandhar-pathi** [mjeanroy/rollup-plugin-prettier#225]
This plugin looks bit different for me.
All rollup plugins use ES6 style of 'import',But this plugin uses CommonJS style 'require'. why ?
I installed the plugin via npm and tried to require as mentioned in the Readme. It doesn't work!!
It says Cannot module rollup.

[!] Error: Cannot find module 'rollup'

i really doubt if Readme is really updated. I observe that you are trying to do it webpack way using path. For rollup it uses relative paths.

**Comment by mjeanroy** [comment]
Hi,

> All rollup plugins use ES6 style of 'import',But this plugin uses CommonJS style 'require'. why ?

Well, in the end, these plugins are transpiled and use `require` statements (as you can see [here](https://github.com/rollup/rollup-plugin-commonjs/blob/58e9aa5822ccb7e4682659617629c46e94ef650f/rollup.config.js#L18)). ES6 imports are still [experimental](https://nodejs.org/api/esm.html) in nodejs 11, and using them would add complexity for now (provide two outputs, one using commonjs, one using ES6 imports for example) for little (no) gain. Once ES6 imports will be officially supported (i.e not experimental), I will add support ES6 modules.

 > [!] Error: Cannot find module 'rollup'

Did you install `rollup` using `npm install --save-dev rollup`?

> i really doubt if Readme is really updated

It is, but if you find some mistakes, feel free to open an issue explaining why you think it is wrong (or even better, feel free to open a PR).

> I observe that you are trying to do it webpack way using path. For rollup it uses relative paths.

I just don't understand what you're saying, and why are you talking about webpack?
