### ISSUE TITLE
Remove lodash?

### ISSUE THREAD

**Issue by charlike** [mjeanroy/rollup-plugin-prettier#33]
It's only used in exactly one place, so it not make any sense to spent time of installing it. Using such util libs and functions is only useful and make sense when 1) you are not sure what type of value is the collection (array/object), 2) or using it in more than 1-2 places, 3) or using more functions for that utils lib.

If you so much want to use lodash (for what reason, i dont see), better would be to use `lodash.foreach` package instead. But it does nothing so magical than Array's `.forEach`, and since the return value of `diffChars` is array, there's no reason of using Lodash or any other thing than the builtin foreach.

Charlike, :wave:

**Comment by mjeanroy** [comment]
@charlike Yes, you're right, lodash is not really needed here.

**Comment by charlike** [comment]
:raised_hands: thanks
