### ISSUE TITLE
Not a module?

### ISSUE THREAD

**Issue by backspaces** [mjeanroy/rollup-plugin-prettier#702]
When I use:
    import prettier from 'rollup-plugin-prettier'
.. I get the error below.

Is this a problem with the repo not having an import that rollup can use? I'm using:
```
        "rollup": "^2.33.1",
        "rollup-plugin-prettier": "^2.1.0",
```
[!] Error: Cannot find module 'prettier'
Require stack:
- /Users/owen/Dropbox/src/agentscript/node_modules/rollup-plugin-prettier/dist/index.js
- /Users/owen/Dropbox/src/agentscript/config/rollup.vendor.js
- /Users/owen/Dropbox/src/agentscript/node_modules/rollup/dist/shared/loadConfigFile.js
- /Users/owen/Dropbox/src/agentscript/node_modules/rollup/dist/bin/rollup

**Comment by mjeanroy** [comment]
@backspaces It looks like you forgot to add `prettier` dependency ([declared as a peer dependency](https://github.com/mjeanroy/rollup-plugin-prettier/blob/69becee8b43a16f7e63974d9d1475d436e26baef/package.json#L31) in `rollup-plugin-prettier`, so you need to install it by yourself).

Try `npm install --save-dev prettier`, it should be ok then :+1:

**Comment by mjeanroy** [comment]
Closing, please comment if needed.
